  set: "flwrlabs/femnist" # to match Hugging face datasets [cifar10, flwrlabs/femnist]
  batch_size: 32
  partition: "natural" # iid, natural
  test_size: 0.2
  validation_size: 0.1 # applied after the test:train split