---
dataset:
  # dataset config
  set: "flwrlabs/femnist" # to match Hugging face datasets [cifar10, flwrlabs/femnist]
  batch_size: 32
  partition: "iid" # iid, dirichlet, natural
  test_size: 0.2
  validation_size: 0.1 # applied after the test:train split
  dirichlet:
    alpha: 0.5
    self_balancing: 1
    min_partition: 10


# need to set up database specific config groups



model:
  lr: 0.01 # need to set up different configs based on different datasets.
  # model config


strategy:
  _target_: # points to your strategy (either custom or exiting in Flower)
  # rest of strategy config
  num_rounds: 5
  num_clients: 10
  fraction_fit: 0.3
  fraction_evaluate: 0.0
  local_epochs: 5
  accept_failures: 0
  ditto_pers_epochs: 5 
  ditto_lambda: 0.8
  ditto_eta: 0.01

client:
  # client config
