---
dataset:
  # dataset config
  batch_size: 32



model:
  # model config


strategy:
  _target_: # points to your strategy (either custom or exiting in Flower)
  # rest of strategy config
  num_rounds: 5
  fraction_fit: 0.3
  fraction_evaluate: 0.0
  num_clients: 10
  local_epochs: 5
  accept_failures: 0
  ditto_pers_epochs: 5 
  ditto_lambda: 0.8
  ditto_eta: 0.01

client:
  # client config
