---
defaults:
  - dataset: femnist # femnist, cifar10
  - _self_ # primary config values will override those from defaults list


model:
  lr: 0.1 # need to set up different configs based on different datasets.
  # model config


strategy:
  _target_: ditto.strategy.Ditto
  num_rounds: 5
  num_clients: 10
  fraction_fit: 0.3
  fraction_evaluate: 0.0
  local_epochs: 5
  accept_failures: 0
  ditto_pers_epochs: 5 
  ditto_lambda: 0.836
  ditto_eta: 0.1

client:
  # client config
